### ISSUE TITLE
Output for opp_get_trips is not projected

### ISSUE THREAD

**Issue by popovs** [popovs/OPPtools#11]
The output for `opp_get_trips` is a SpatialPointsDataFrame with an associated proj4string, but running `sp::is.projected` returns `FALSE`.

Running the same function on the output from `ctcrw_interpolation` returns `TRUE`, e.g. `sp::is.projected(interp_output$data)` and `sp::is.projected(interp_output$interp)` are both `TRUE`!

At the moment this is a minor inconvenience as it means `opp_kernel` cannot calculate kernels on `opp_get_trips` outputs, only on `ctcrw_interpolation` outputs.

**Comment by allisonglider** [comment]
This was done intentionally to match the behaviour of track2KBA::splitTrips. I'm not sure if it is the behaviour we would ultimately want from the function. Since kernels shouldn't really be run on the irregular data, maybe it's OK?
