### ISSUE TITLE
Clean up BLOY data on Movebank

### ISSUE THREAD

**Issue by allisonglider** [popovs/OPPtools#43]
Movebank project ID: 696824680

Banding data on Google Drive: https://drive.google.com/drive/u/0/folders/1D3fU8RECZdcXZFctZtJaB_JKF11mIq17

Start with formatting reference data (movebank project data are sparse), then work with Hannah Roodenrijs on location data.

**Comment by popovs** [comment]
Need to either swap lat/longs for a few locations and/or update the deployment on times. Got a few wonky locations!

![image](https://user-images.githubusercontent.com/19844383/158442888-17f2b2f7-5316-48af-bbc3-1db0ac654006.png)

**Comment by popovs** [comment]
After cutting out outlier & incorrect lat/longs, we have the following map. From this map there appear to be potentially 4 geographic clusters, and it may be worth splitting the dataset apart to run 4 discrete exploratory analyses.

![image](https://user-images.githubusercontent.com/19844383/158452693-c86fbed7-709c-411c-ad57-fc8e2dc0b5f1.png)

**Comment by allisonglider** [comment]
All data have been added to project and filtered according to PI priorities. Project includes a README with any data issues
