### ISSUE TITLE
GWGU Maps

### ISSUE THREAD

**Issue by allisonglider** [popovs/OPPtools#54]
Request for maps for an annual report:

I can take a look at the tracks and see if a bird has done anything interesting – such as utilizing multiple habitat types, high site fidelity to a landfill, migration, etc.

Map ideas and where we would like to focus, if possible:
-          GWGU tagged on the West Coast of Vancouver Island (Tofino/Ucluelet) in 2022
-          Gull(s) heading for breeding grounds in Alaska in 2022
-          Fine scale movement map – this could be a gull tagged at a Landfill or natural area
-          Gull tagged at a landfill in 2020 or 2021, with interesting track in 2022
-          CAGU tagged at the Nanaimo Landfill

I can give you more specifics to include once I’ve had a look at the recent Movebank data. However, please feel free to let me know if something exciting pops out at you when you get a chance to look at the data. And as always don’t hesitate to reach out with questions.

**Comment by popovs** [comment]
Followup from Anneka:

> The gulls of interest I saw on Movebank are:
> -          2406-09333 tagged in 2021 (migrated to Alaska for a second year)
> -          2406-09331 tagged in 2021 (Howe Sound, Sechelt/Jervis inlet tracks)
> -          1216-01024 tagged in 2020 – tag may have failed last August but I saw a few pings in March of this year (spends time around Vancouver Island and Central Coast).
