### ISSUE TITLE
Reproject output from `opp_get_trips` and `opp_sites` to EPSG4326/WGS84

### ISSUE THREAD

**Issue by popovs** [popovs/OPPtools#67]
All final OPP data products should be in EPSG4326/WGS84 projection. Code for `opp_get_trips` and `opp_sites` should either be updated to output 4326 products, or additional lines of code should be written into the KBA `skeleton.Rmd` file to re-project geospatial products before saving as shapefiles.

Linked to issue #66

**Comment by allisonglider** [comment]
I think we should do this in the skeleton, so it doesn't change the inputs for any downstream functions. I think the opp_sites output is already in 4326, but not 100% certain of that.
